language: node_js
node_js:
- 10
script:
- npm install
- npm run build-dev
branches:
  only:
  - travis
before_install:
- openssl aes-256-cbc -K $encrypted_36f4c5c8b0dd_key -iv $encrypted_36f4c5c8b0dd_iv
  -in 2018_2_SimpleName_id_rsa.pem.enc -out ~\/\З\а\г\р\у\з\к\и/Telegram\ Desktop/2018_2_SimpleName_id_rsa.pem
  -d
